apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: kube-system
data:
  token: kJiUIqzt38eczEOfUYjKv8B+VY0ZlKHeLRLh6esOKj4=
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://hv.konkas.tech:8200/"
      path: "expense"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: kube-system