apiVersion: v1
kind: Service
metadata:
  name: dev-frontend
  labels:
    app: frontend
    tier: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
      app: frontend
      tier: web