{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expense-yaml
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: "{{ .Values.alb.name }}"
    alb.ingress.kubernetes.io/group.name: "{{ .Values.alb.group }}"
    alb.ingress.kubernetes.io/scheme: "{{ .Values.alb.scheme }}"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: "Environment={{ .Values.env }},Team={{ .Values.name}}"
    alb.ingress.kubernetes.io/group.order: '10'
    alb.ingress.kubernetes.io/healthcheck-path: '/'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.alb.certificateArn }}"
    alb.ingress.kubernetes.io/ssl-policy: 'ELBSecurityPolicy-2016-08'
    alb.ingress.kubernetes.io/actions.ssl-redirect: >
      {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301" }}
    external-dns.alpha.kubernetes.io/hostname: '{{ .Values.dns.hostname }}'
    external-dns.alpha.kubernetes.io/ttl: '60'
spec:
  ingressClassName: alb
  rules:
    - host: "{{ .Values.dns.hostname }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
{{- end }}
