# {{- if .Values.secrets.enabled }}
# {{- range .Values.secrets.list }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ $.Values.env }}-{{ $.Values.name }}
#   labels:
#     {{- toYaml $.Values.labels | nindent 4 }}
# type: Opaque
# data:
#   {{- range $key, $value := .data }}
#   {{ $key }}: {{ $value | b64enc }}
#   {{- end }}
# ---
# {{- end }}
# {{- end }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.env}}-{{ .Values.name}}
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.env}}-{{ .Values.name}}
  dataFrom:
  - extract:
      key: backend