apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        project: expense
    spec:
      containers:
        - name: backend
          image: siva9666/expense-backend:node
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              memory: 500Mi
              cpu: 100m
            limits:
              memory: 600Mi
              cpu: 200m
