apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-backend
  labels:
    app: backend
    tier: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: application
  template:
    metadata:
      labels:
        app: backend
        tier: application
    spec:
      containers:
        - name: dev-backend
          image: "siva9666/expense-backend:node"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 75m
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: dev-backend
            - secretRef:
                name: dev-backend