apiVersion: v1
kind: Service
metadata:
  name: dev-backend
  labels:
    app: backend
    tier: application
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
      app: backend
      tier: application