apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    project: instana
    tier: shipping-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: shipping-backend
  template:
    metadata:
      labels:
        tier: shipping-backend
    spec:
      containers:
        - name: shipping
          image: 522814728660.dkr.ecr.ap-south-1.amazonaws.com/instana/shipping:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: 800m
            limits:
              memory: "2Gi"
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 40      
            periodSeconds: 10           
            timeoutSeconds: 2           
            successThreshold: 1
            failureThreshold: 3          
          livenessProbe:
            httpGet:
              path: /health             
              port: 8080
            initialDelaySeconds: 40
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: shipping-config
            - secretRef:
                name: shipping-secrets
# - describe the pod
# - checks the logs
# - cross check the secrets and cm mounted well
# - check the probes are successfully executed
# - some times probes also casuses the issues becase initial delay seconds less no of seconds for health check start