apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    project: instana
    tier: shipping-backend
spec:
  selector:
    tier: shipping-backend
  ports:
    - port: 8080
      targetPort: 8080